### ISSUE TITLE
Help feature in GUI

### ISSUE THREAD

**Issue by FPriceGithub** [teamevolve/EVOLVE#24]
Should have an introduction to the program and that we'll need a new, “Introduction” button to bring up Help01 Introduction.rtf. Can you put that at the top center of the GUI?

I've put these help files into the GUI folder:
- Help01 Introduction.rtf
- Help02 Exp Config.rtf
- Help03 Initial Pop.rtf
- Help04 Drift.rtf
- Help05 Natural Selection.rtf
- Help06 Mutation.rtf
- Help07 Migration.rtf
- Help08 Sexual Selection.rtf
- Help09 Graphs.rtf 

Clicking on the existing help button should bring up the Help02 file; a “Help” button in Initial Population panel will bring up a Help03 Initial Pop.rtf file, etc.

When make jar, 
If PDF > copy to runnable
	Else if RTF & Libreoffice installed  compile rtf > PDF
	Else no help

**Comment by adennis96** [comment]
Resolved as of [5f0558a](https://github.com/teamevolve/EVOLVE/commit/5f0558a3be9fcae86e48583d0be5a124a635b321)
