### ISSUE TITLE
Initial seed not retained for subsequent experiments

### ISSUE THREAD

**Issue by FPriceGithub** [teamevolve/EVOLVE#33]
It appears that the initial random number is not used for subsequent experiments.
The initial random number seed shown in the input window should be used in subsequent runs.
I.e., if the Run Simulation button is pressed repeatedly with no changes in inputs, the graphs should be identical.
Retyping the same number and input box is not a workaround.
The objective of this is to allow students to repeat experiments, e.g., to show a faculty member what happened. See the help file documentation on the Seed.

**Comment by cx-zhao** [comment]
fixed as of [https://github.com/teamevolve/EVOLVE/commit/0856dd083a2b1159f7e3d129dff21d2d8b099099](url)

**Comment by cx-zhao** [comment]
fixed as of 0856dd0
