### ISSUE TITLE
Export Data: export all inputs

### ISSUE THREAD

**Issue by FPriceGithub** [teamevolve/EVOLVE#41]
Should export all input data values, even those that were not changed, e.g., mutation rates of zero when mutation has not been checked.

2017/11/28 update:
1. Mating preferences (no input) still exported as 
SEXUAL SEL.			Total
AA Pref.	0.333333333	0.333333333	0.333333333	1
AB Pref.	0.333333333	0.333333333	0.333333333	1
BB Pref.	0.333333333	0.333333333	0.333333333	1
2. I checked the Sexual Selection box, set values for mating preferences & they exported properly.
3. I unchecked  the Sexual Selection box, & the exported data were as above.
4. Just noticed that the Lab Notebook fields still don't export if they have no input & they should. Students should be able to run a simulation, add notes, then export fields' contents along with the data.

The reason I think we should have all fields in the same cells of exported data files is that students might want to have other programs, whether Excel, R, or a stat package, do more sophisticated  analyses & graphics. That will be easier if specific data are always in exactly the same location.

**Comment by cx-zhao** [comment]
fixed as of 733a712
